package org.nostr.nostrord.ui.screens.login

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import org.nostr.nostrord.auth.Account
import org.nostr.nostrord.auth.pomegranate.PomegranateAccountConfig
import org.nostr.nostrord.auth.pomegranate.PomegranateConfig
import org.nostr.nostrord.auth.pomegranate.PomegranateService
import org.nostr.nostrord.auth.pomegranate.PomegranateStatus
import org.nostr.nostrord.network.NostrRepositoryApi
import org.nostr.nostrord.nostr.Crypto
import org.nostr.nostrord.nostr.KeyPair
import org.nostr.nostrord.nostr.NIP55_PERMISSIONS
import org.nostr.nostrord.nostr.Nip07
import org.nostr.nostrord.nostr.Nip19
import org.nostr.nostrord.nostr.Nip46Client
import org.nostr.nostrord.nostr.Nip49
import org.nostr.nostrord.nostr.Nip55
import org.nostr.nostrord.nostr.hexToByteArray
import org.nostr.nostrord.nostr.ncryptsecStorageApplicable
import org.nostr.nostrord.nostr.toHexString
import org.nostr.nostrord.storage.SecureStorage
import org.nostr.nostrord.storage.getEncryptedPrivateKeyFor
import org.nostr.nostrord.storage.getNostrConnectRelays
import org.nostr.nostrord.storage.saveNostrConnectRelays
import org.nostr.nostrord.storage.savePomegranateCentralFor
import org.nostr.nostrord.utils.toKotlinResult

/**
 * Screen logic for login, shared by the Compose UI (android/jvm/ios) and the React web
 * UI. Lives in commonMain so all login modes (private key, NIP-46 bunker QR/URL, NIP-07
 * extension) are written and tested once; each platform's screen is only layout. Compose
 * obtains it via `viewModel { }`, web via `useViewModel { }`.
 */
class LoginViewModel(
    private val repo: NostrRepositoryApi,
    private val pomegranate: PomegranateService = PomegranateService(),
) : ViewModel() {
    val authUrl: StateFlow<String?> = repo.authUrl

    private val _qrUri = MutableStateFlow<String?>(null)
    val qrUri: StateFlow<String?> = _qrUri.asStateFlow()

    private var qrJob: Job? = null

    /**
     * The active QR-flow Nip46Client. Tracked here so [cancelQrSession] can
     * tear its WebSocket connections down — the durable response subscription
     * stays open until disconnect, so simply cancelling [qrJob] is not enough.
     */
    private var qrClient: Nip46Client? = null

    // Relays used to seed the nostrconnect:// QR. Starts from the user's saved
    // list (if any) or the defaults; editable in the QR screen and persisted so
    // a flaky default relay can be replaced once and remembered.
    private val _nostrConnectRelays =
        MutableStateFlow(SecureStorage.getNostrConnectRelays() ?: repo.defaultNostrConnectRelays)
    val nostrConnectRelays: StateFlow<List<String>> = _nostrConnectRelays.asStateFlow()

    /** Update and persist the nostrconnect relays. The QR is regenerated by the
     * caller restarting the session (which reads the new list). */
    fun setNostrConnectRelays(relays: List<String>) {
        val cleaned = relays.map { it.trim() }.filter { it.isNotEmpty() }.distinct()
        if (cleaned.isEmpty()) return
        _nostrConnectRelays.value = cleaned
        SecureStorage.saveNostrConnectRelays(cleaned)
    }

    fun clearAuthUrl() = repo.clearAuthUrl()

    fun loginWithPrivateKey(
        privKey: String,
        pubKey: String,
        isNewIdentity: Boolean = false,
        ncryptsec: String? = null,
        onResult: (Result<Unit>) -> Unit,
    ) {
        viewModelScope.launch {
            onResult(repo.loginSuspend(privKey, pubKey, isNewIdentity, ncryptsec).toKotlinResult())
        }
    }

    /** True when the input is a NIP-49 encrypted key; the UIs ask for [loginWithPrivateKeyInput]'s password. */
    fun isEncryptedKeyInput(input: String): Boolean = Nip49.isEncryptedKey(input)

    /** True for a plain (hex / nsec) key — the UIs offer the protect-with-password option for these. */
    fun isPlainKeyInput(input: String): Boolean = isValidKeyInput(input) && !Nip49.isEncryptedKey(input)

    /**
     * True where the protect-with-password option (ncryptsec at rest + unlock at
     * startup) makes sense: only the web. Native platforms already protect keys at
     * rest (Keystore / Keychain / OS keychain), so the UIs hide the option there and
     * an imported ncryptsec is decrypted once into the platform's secure storage.
     */
    val isProtectApplicable: Boolean get() = ncryptsecStorageApplicable

    /** Fresh private key from the platform CSPRNG (the generate flow; not kotlin.random). */
    fun generateNewKeyHex(): String = Crypto.generatePrivateKey().toHexString()

    /** npub + nsec for displaying a key backup; null when the hex is invalid. */
    fun deriveBech32Keys(hexOrNsec: String): Pair<String, String>? {
        val hex = parsePrivateKeyHex(hexOrNsec) ?: return null
        return try {
            Nip19.encodeNpub(KeyPair.fromPrivateKeyHex(hex).publicKeyHex) to Nip19.encodeNsec(hex)
        } catch (e: Throwable) {
            null
        }
    }

    /**
     * Login with a plain (hex / nsec) key in password-protected mode: the key is
     * wrapped as an ncryptsec (NIP-49, scrypt on the Default dispatcher), only the
     * encrypted form is persisted, and the next session restore asks the password
     * via [pendingUnlock].
     */
    fun loginProtected(
        input: String,
        password: String,
        isNewIdentity: Boolean = false,
        onResult: (Result<Unit>) -> Unit,
    ) {
        val hex = parsePrivateKeyHex(input)
        if (hex == null) {
            onResult(Result.failure(IllegalArgumentException("Invalid private key")))
            return
        }
        viewModelScope.launch {
            val ncryptsec = withContext(Dispatchers.Default) { Nip49.encrypt(hex.hexToByteArray(), password) }
            loginWithHex(hex, isNewIdentity, ncryptsec, onResult)
        }
    }

    /** Account waiting for its NIP-49 password at startup (drives the unlock dialog). */
    val pendingUnlock: StateFlow<Account?> = repo.pendingUnlockAccount

    /** Dismiss the unlock dialog; the user falls back to the regular login screen. */
    fun dismissUnlock() = repo.clearPendingUnlock()

    /**
     * Decrypt the pending account's stored ncryptsec with [password] and finish the
     * session restore. Fails with "Wrong password or corrupted key" on a bad password.
     */
    fun unlockWithPassword(
        password: String,
        onResult: (Result<Unit>) -> Unit,
    ) {
        val account = repo.pendingUnlockAccount.value
        if (account == null) {
            onResult(Result.failure(IllegalStateException("No account to unlock")))
            return
        }
        val ncryptsec = SecureStorage.getEncryptedPrivateKeyFor(account.pubkey)
        if (ncryptsec == null) {
            onResult(Result.failure(IllegalStateException("No encrypted key stored")))
            return
        }
        loginWithPrivateKeyInput(ncryptsec, password, onResult = onResult)
    }

    /**
     * True when the input is a complete, well-formed key: 64-char hex, a decodable
     * nsec, or a structurally valid ncryptsec. The UIs gate the Login button on this
     * so partial or garbage input never produces an "Invalid private key" round trip.
     */
    fun isValidKeyInput(input: String): Boolean {
        val s = input.trim()
        return if (Nip49.isEncryptedKey(s)) Nip49.hasValidStructure(s) else parsePrivateKeyHex(s) != null
    }

    /**
     * Accepts a raw nsec, 64-char hex, or NIP-49 ncryptsec private key, derives the
     * public key, and logs in. ncryptsec requires [password]; scrypt runs on the
     * Default dispatcher because the default log_n = 16 costs real CPU and memory.
     * The parsing lives here (not per-UI) so Compose and web validate identically.
     */
    fun loginWithPrivateKeyInput(
        input: String,
        password: String? = null,
        isNewIdentity: Boolean = false,
        onResult: (Result<Unit>) -> Unit,
    ) {
        if (Nip49.isEncryptedKey(input)) {
            if (password.isNullOrEmpty()) {
                onResult(Result.failure(IllegalArgumentException("Enter the key password")))
                return
            }
            viewModelScope.launch {
                val trimmed = input.trim()
                val keyBytes = withContext(Dispatchers.Default) { Nip49.decrypt(trimmed, password) }
                if (keyBytes == null) {
                    onResult(Result.failure(IllegalArgumentException("Wrong password or corrupted key")))
                } else {
                    // On the web an ncryptsec login keeps the account password-protected
                    // (only the encrypted key is persisted; unlock asked at next startup).
                    // Native platforms store the decrypted key in Keystore / keychain
                    // instead, so the NIP-49 password is needed only for this import.
                    val persistEncrypted = trimmed.takeIf { ncryptsecStorageApplicable }
                    loginWithHex(keyBytes.toHexString(), isNewIdentity, ncryptsec = persistEncrypted, onResult)
                }
            }
            return
        }
        val hex = parsePrivateKeyHex(input)
        if (hex == null) {
            onResult(Result.failure(IllegalArgumentException("Invalid private key")))
            return
        }
        loginWithHex(hex, isNewIdentity, ncryptsec = null, onResult)
    }

    private fun loginWithHex(
        hex: String,
        isNewIdentity: Boolean,
        ncryptsec: String?,
        onResult: (Result<Unit>) -> Unit,
    ) {
        val pub =
            try {
                KeyPair.fromPrivateKeyHex(hex).publicKeyHex
            } catch (e: Throwable) {
                onResult(Result.failure(IllegalArgumentException("Invalid private key")))
                return
            }
        loginWithPrivateKey(hex, pub, isNewIdentity, ncryptsec, onResult)
    }

    fun loginWithNip07(
        pubkey: String,
        onResult: (Result<Unit>) -> Unit,
    ) {
        viewModelScope.launch {
            onResult(repo.loginWithNip07(pubkey).toKotlinResult())
        }
    }

    fun loginWithNip07Extension(onResult: (Result<Unit>) -> Unit) {
        viewModelScope.launch {
            try {
                val pubkey = Nip07.getPublicKey() // platform call — can throw if extension unavailable
                onResult(repo.loginWithNip07(pubkey).toKotlinResult())
            } catch (c: CancellationException) {
                throw c
            } catch (e: Exception) {
                onResult(Result.failure(e))
            }
        }
    }

    /** True where "Login with Amber" (NIP-55 external signer) can run: Android with a signer installed. */
    val isAmberLoginAvailable: Boolean get() = Nip55.isAvailable()

    /**
     * Login via the NIP-55 Android signer (Amber): opens its account picker, requests
     * the app's permission set (so later signs run silently), and registers the account.
     */
    fun loginWithAmber(onResult: (Result<Unit>) -> Unit) {
        viewModelScope.launch {
            try {
                val login = Nip55.getPublicKey(NIP55_PERMISSIONS)
                onResult(repo.loginWithAmber(login.pubkeyHex, login.signerPackage).toKotlinResult())
            } catch (c: CancellationException) {
                throw c
            } catch (e: Exception) {
                onResult(Result.failure(e))
            }
        }
    }

    fun loginWithBunker(
        url: String,
        onResult: (Result<Unit>) -> Unit,
    ) {
        viewModelScope.launch {
            onResult(repo.loginWithBunker(url).map { }.toKotlinResult())
        }
    }

    /** True where "Login with Google" (pomegranate) can run: the web, with the flag on. */
    val isGoogleLoginAvailable: Boolean get() = pomegranate.isAvailable

    /**
     * Non-null while the Google flow waits on the "Create your account" step: this Google
     * identity has no account yet, so the user backs up the generated key and can review
     * the operators before anything is registered.
     */
    private val _googleSetup = MutableStateFlow<GoogleAccountSetup?>(null)
    val googleSetup: StateFlow<GoogleAccountSetup?> = _googleSetup.asStateFlow()

    /** The authenticated Google token the setup step will create the account with. */
    private var startedGoogleLogin: PomegranateService.StartedLogin? = null

    private var operatorCheckJob: Job? = null
    private var createAccountJob: Job? = null

    /**
     * Login with Google via the pomegranate threshold signer. The popup mints a token; an
     * existing account logs straight in over the resulting `bunker://` URL, a first-time
     * one stops at [googleSetup] and finishes in [createGoogleAccount]. Must be called
     * from a click handler; a popup opened outside a user gesture is blocked.
     */
    fun loginWithGoogle(
        centralUrl: String = PomegranateConfig.CENTRAL_URL,
        onStatus: (PomegranateStatus) -> Unit,
        onNewAccount: () -> Unit = {},
        onResult: (Result<Unit>) -> Unit,
    ) {
        viewModelScope.launch {
            try {
                val started = pomegranate.startLogin(centralUrl, onStatus = onStatus)
                if (!started.hasAccount) {
                    startedGoogleLogin = started
                    _googleSetup.value = newGoogleSetup()
                    onNewAccount()
                    return@launch
                }
                // Existing account: its operators are fixed server-side, nothing to configure.
                finishGoogleLogin(started, config = null, onStatus = onStatus)
                onResult(Result.success(Unit))
            } catch (c: CancellationException) {
                throw c
            } catch (t: Throwable) {
                // Throwable, not Exception: popup/dealer failures can surface as raw JS errors.
                onResult(Result.failure(t))
            }
        }
    }

    /**
     * Registers the new account with the key and operator config in [googleSetup], then
     * logs in with it. Reuses the token from [loginWithGoogle], so no second Google popup.
     */
    fun createGoogleAccount(
        onStatus: (PomegranateStatus) -> Unit,
        onResult: (Result<Unit>) -> Unit,
    ) {
        val started = startedGoogleLogin
        val setup = _googleSetup.value
        if (started == null || setup == null) {
            onResult(Result.failure(IllegalStateException("Sign in with Google again to continue")))
            return
        }
        // The button disables itself, but a frozen frame can still queue a second tap, and a
        // second /register races the first into a 409 from the central.
        if (createAccountJob?.isActive == true) return
        createAccountJob = viewModelScope.launch {
            try {
                finishGoogleLogin(started, setup.toConfig(), onStatus)
                onResult(Result.success(Unit))
            } catch (c: CancellationException) {
                throw c
            } catch (t: Throwable) {
                onResult(Result.failure(t))
            }
        }
    }

    /** Leaves the setup step (Back); the next attempt signs in with Google again. */
    fun cancelGoogleSetup() {
        operatorCheckJob?.cancel()
        operatorCheckJob = null
        startedGoogleLogin = null
        _googleSetup.value = null
    }

    /** Replaces the offered key with a fresh one; the shown nsec is what gets registered. */
    fun regenerateGoogleKey() {
        _googleSetup.update { current ->
            current?.let { newGoogleSetup(it.operators, it.threshold).copy(operatorStatus = it.operatorStatus) }
        }
    }

    /**
     * Shards an identity the user already has instead of the generated one: they paste its
     * nsec or hex and the account is created for that pubkey. Returns the error message
     * when the input is not a usable key. An ncryptsec is rejected here — it needs its
     * password, which the private-key login handles.
     */
    fun importGoogleKey(input: String): String? {
        if (_googleSetup.value == null) return null
        val hex = parsePrivateKeyHex(input) ?: return "Enter a valid nsec or 64-character hex key"
        _googleSetup.update { it?.withImportedKey(hex, Nip19.encodeNsec(hex)) }
        return null
    }

    /** Adds an operator to the new account; returns the error message when it can't be added. */
    fun addGoogleOperator(raw: String): String? {
        val setup = _googleSetup.value ?: return null
        val next = setup.withOperatorAdded(raw)
        next.getOrNull()?.let {
            _googleSetup.value = it
            checkGoogleOperators()
        }
        return next.exceptionOrNull()?.message
    }

    /**
     * Probes the listed operators so a host that is down is named in the setup step rather
     * than surfacing as a failed registration. The screens run it when the step opens and
     * after an operator is added; it is also the Retry action on the warning.
     */
    fun checkGoogleOperators() {
        val setup = _googleSetup.value ?: return
        operatorCheckJob?.cancel()
        _googleSetup.value = setup.checking()
        operatorCheckJob =
            viewModelScope.launch {
                val results =
                    pomegranate.checkOperators(setup.operators).associate { health ->
                        health.url to
                            if (health.reachable) {
                                GoogleAccountSetup.OperatorStatus.Reachable
                            } else {
                                GoogleAccountSetup.OperatorStatus.Unreachable
                            }
                    }
                _googleSetup.update { it?.withStatuses(results) }
            }
    }

    fun removeGoogleOperator(url: String) {
        _googleSetup.update { it?.withOperatorRemoved(url) }
    }

    fun setGoogleThreshold(value: Int) {
        _googleSetup.update { it?.withThreshold(value) }
    }

    private fun newGoogleSetup(
        operators: List<String> = PomegranateConfig.OPERATOR_URLS,
        threshold: Int = PomegranateConfig.defaultThreshold(operators.size),
    ): GoogleAccountSetup {
        val hex = generateNewKeyHex()
        return GoogleAccountSetup(hex, Nip19.encodeNsec(hex), operators, threshold)
    }

    /** Creates the account when needed, logs in over its bunker URL, and clears the setup step. */
    private suspend fun finishGoogleLogin(
        started: PomegranateService.StartedLogin,
        config: PomegranateAccountConfig?,
        onStatus: (PomegranateStatus) -> Unit,
    ) {
        val outcome = pomegranate.finishLogin(started, config, onStatus)
        onStatus(PomegranateStatus.Connecting)
        val pubkey = repo.loginWithBunker(outcome.bunkerUrl).toKotlinResult().getOrThrow()
        SecureStorage.savePomegranateCentralFor(pubkey, outcome.central)
        cancelGoogleSetup()
    }

    fun startQrSession(
        onConnected: () -> Unit,
        onError: (String?) -> Unit,
    ) {
        qrJob?.cancel()
        qrClient?.disconnect()
        qrClient = null
        _qrUri.value = null
        qrJob =
            viewModelScope.launch {
                try {
                    // Retry the relay connect a few times: logging out tears down many
                    // sockets at once, and the browser keeps the just-closed ones in a
                    // CLOSING state that still counts against its per-host WebSocket
                    // limit, so a connect attempted right after a logout can fail until
                    // they free up. A short backoff recovers without an app restart.
                    val (uri, client) = createSessionWithRetry()
                    qrClient = client
                    _qrUri.value = uri
                    repo.completeNostrConnectLogin(client)
                    qrClient = null
                    onConnected()
                } catch (c: CancellationException) {
                    // Scope/job cancelled (screen left, Try Again, relay re-apply): tear the
                    // socket down and propagate — never report it as a connection failure.
                    qrClient?.disconnect()
                    qrClient = null
                    throw c
                } catch (e: Exception) {
                    qrClient?.disconnect()
                    qrClient = null
                    onError("Connection failed: ${e.message}")
                }
            }
    }

    private suspend fun createSessionWithRetry(): Pair<String, Nip46Client> {
        var lastError: Exception? = null
        repeat(QR_CONNECT_ATTEMPTS) { attempt ->
            try {
                return repo.createNostrConnectSession(_nostrConnectRelays.value)
            } catch (c: CancellationException) {
                throw c
            } catch (e: Exception) {
                lastError = e
                if (attempt < QR_CONNECT_ATTEMPTS - 1) delay(QR_CONNECT_RETRY_DELAY_MS)
            }
        }
        throw lastError ?: Exception("Failed to connect to any relay")
    }

    fun cancelQrSession() {
        qrJob?.cancel()
        qrClient?.disconnect()
        qrClient = null
        _qrUri.value = null
    }

    override fun onCleared() {
        super.onCleared()
        qrJob?.cancel()
        qrClient?.disconnect()
        qrClient = null
    }

    private companion object {
        const val HEX_CHARS = "0123456789abcdefABCDEF"

        // Bounded retry for the nostrconnect relay connect, to ride out the brief
        // post-logout window where just-closed sockets still hold the browser's
        // per-host WebSocket slots.
        const val QR_CONNECT_ATTEMPTS = 3
        const val QR_CONNECT_RETRY_DELAY_MS = 1_500L

        /** Accepts an nsec or a 64-char hex private key; returns the hex, or null if invalid. */
        fun parsePrivateKeyHex(input: String): String? {
            val s = input.trim()
            return when {
                s.startsWith("nsec1") -> (Nip19.decode(s) as? Nip19.Entity.Nsec)?.privkey
                s.length == 64 && s.all { it in HEX_CHARS } -> s.lowercase()
                else -> null
            }
        }
    }
}
