package org.nostr.nostrord.ui.screens.login

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Job
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import org.nostr.nostrord.network.NostrRepositoryApi
import org.nostr.nostrord.nostr.KeyPair
import org.nostr.nostrord.nostr.Nip07
import org.nostr.nostrord.nostr.Nip19
import org.nostr.nostrord.nostr.Nip46Client
import org.nostr.nostrord.storage.SecureStorage
import org.nostr.nostrord.storage.getNostrConnectRelays
import org.nostr.nostrord.storage.saveNostrConnectRelays
import org.nostr.nostrord.utils.toKotlinResult

/**
 * Screen logic for login, shared by the Compose UI (android/jvm/ios) and the React web
 * UI. Lives in commonMain so all login modes (private key, NIP-46 bunker QR/URL, NIP-07
 * extension) are written and tested once; each platform's screen is only layout. Compose
 * obtains it via `viewModel { }`, web via `useViewModel { }`.
 */
class LoginViewModel(
    private val repo: NostrRepositoryApi,
) : ViewModel() {
    val authUrl: StateFlow<String?> = repo.authUrl

    private val _qrUri = MutableStateFlow<String?>(null)
    val qrUri: StateFlow<String?> = _qrUri.asStateFlow()

    private var qrJob: Job? = null

    /**
     * The active QR-flow Nip46Client. Tracked here so [cancelQrSession] can
     * tear its WebSocket connections down — the durable response subscription
     * stays open until disconnect, so simply cancelling [qrJob] is not enough.
     */
    private var qrClient: Nip46Client? = null

    // Relays used to seed the nostrconnect:// QR. Starts from the user's saved
    // list (if any) or the defaults; editable in the QR screen and persisted so
    // a flaky default relay can be replaced once and remembered.
    private val _nostrConnectRelays =
        MutableStateFlow(SecureStorage.getNostrConnectRelays() ?: repo.defaultNostrConnectRelays)
    val nostrConnectRelays: StateFlow<List<String>> = _nostrConnectRelays.asStateFlow()

    /** Update and persist the nostrconnect relays. The QR is regenerated by the
     * caller restarting the session (which reads the new list). */
    fun setNostrConnectRelays(relays: List<String>) {
        val cleaned = relays.map { it.trim() }.filter { it.isNotEmpty() }.distinct()
        if (cleaned.isEmpty()) return
        _nostrConnectRelays.value = cleaned
        SecureStorage.saveNostrConnectRelays(cleaned)
    }

    fun clearAuthUrl() = repo.clearAuthUrl()

    fun loginWithPrivateKey(
        privKey: String,
        pubKey: String,
        isNewIdentity: Boolean = false,
        onResult: (Result<Unit>) -> Unit,
    ) {
        viewModelScope.launch {
            onResult(repo.loginSuspend(privKey, pubKey, isNewIdentity).toKotlinResult())
        }
    }

    /**
     * Accepts a raw nsec or 64-char hex private key, derives the public key, and logs in.
     * The parsing lives here (not per-UI) so Compose and web validate identically.
     */
    fun loginWithPrivateKeyInput(
        input: String,
        isNewIdentity: Boolean = false,
        onResult: (Result<Unit>) -> Unit,
    ) {
        val hex = parsePrivateKeyHex(input)
        if (hex == null) {
            onResult(Result.failure(IllegalArgumentException("Invalid private key")))
            return
        }
        val pub =
            try {
                KeyPair.fromPrivateKeyHex(hex).publicKeyHex
            } catch (e: Throwable) {
                onResult(Result.failure(IllegalArgumentException("Invalid private key")))
                return
            }
        loginWithPrivateKey(hex, pub, isNewIdentity, onResult)
    }

    fun loginWithNip07(
        pubkey: String,
        onResult: (Result<Unit>) -> Unit,
    ) {
        viewModelScope.launch {
            onResult(repo.loginWithNip07(pubkey).toKotlinResult())
        }
    }

    fun loginWithNip07Extension(onResult: (Result<Unit>) -> Unit) {
        viewModelScope.launch {
            try {
                val pubkey = Nip07.getPublicKey() // platform call — can throw if extension unavailable
                onResult(repo.loginWithNip07(pubkey).toKotlinResult())
            } catch (c: CancellationException) {
                throw c
            } catch (e: Exception) {
                onResult(Result.failure(e))
            }
        }
    }

    fun loginWithBunker(
        url: String,
        onResult: (Result<Unit>) -> Unit,
    ) {
        viewModelScope.launch {
            onResult(repo.loginWithBunker(url).map { }.toKotlinResult())
        }
    }

    fun startQrSession(
        onConnected: () -> Unit,
        onError: (String?) -> Unit,
    ) {
        qrJob?.cancel()
        qrClient?.disconnect()
        qrClient = null
        _qrUri.value = null
        qrJob =
            viewModelScope.launch {
                try {
                    val (uri, client) = repo.createNostrConnectSession(_nostrConnectRelays.value)
                    qrClient = client
                    _qrUri.value = uri
                    repo.completeNostrConnectLogin(client)
                    qrClient = null
                    onConnected()
                } catch (c: CancellationException) {
                    // Scope/job cancelled (screen left, Try Again, relay re-apply): tear the
                    // socket down and propagate — never report it as a connection failure.
                    qrClient?.disconnect()
                    qrClient = null
                    throw c
                } catch (e: Exception) {
                    qrClient?.disconnect()
                    qrClient = null
                    onError("Connection failed: ${e.message}")
                }
            }
    }

    fun cancelQrSession() {
        qrJob?.cancel()
        qrClient?.disconnect()
        qrClient = null
        _qrUri.value = null
    }

    override fun onCleared() {
        super.onCleared()
        qrJob?.cancel()
        qrClient?.disconnect()
        qrClient = null
    }

    private companion object {
        const val HEX_CHARS = "0123456789abcdefABCDEF"

        /** Accepts an nsec or a 64-char hex private key; returns the hex, or null if invalid. */
        fun parsePrivateKeyHex(input: String): String? {
            val s = input.trim()
            return when {
                s.startsWith("nsec1") -> (Nip19.decode(s) as? Nip19.Entity.Nsec)?.privkey
                s.length == 64 && s.all { it in HEX_CHARS } -> s.lowercase()
                else -> null
            }
        }
    }
}
