package org.nostr.nostrord.ui.screens.login

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import org.nostr.nostrord.auth.Account
import org.nostr.nostrord.network.NostrRepositoryApi
import org.nostr.nostrord.nostr.Crypto
import org.nostr.nostrord.nostr.KeyPair
import org.nostr.nostrord.nostr.Nip07
import org.nostr.nostrord.nostr.Nip19
import org.nostr.nostrord.nostr.Nip46Client
import org.nostr.nostrord.nostr.Nip49
import org.nostr.nostrord.nostr.hexToByteArray
import org.nostr.nostrord.nostr.toHexString
import org.nostr.nostrord.storage.SecureStorage
import org.nostr.nostrord.storage.getEncryptedPrivateKeyFor
import org.nostr.nostrord.storage.getNostrConnectRelays
import org.nostr.nostrord.storage.saveNostrConnectRelays
import org.nostr.nostrord.utils.toKotlinResult

/**
 * Screen logic for login, shared by the Compose UI (android/jvm/ios) and the React web
 * UI. Lives in commonMain so all login modes (private key, NIP-46 bunker QR/URL, NIP-07
 * extension) are written and tested once; each platform's screen is only layout. Compose
 * obtains it via `viewModel { }`, web via `useViewModel { }`.
 */
class LoginViewModel(
    private val repo: NostrRepositoryApi,
) : ViewModel() {
    val authUrl: StateFlow<String?> = repo.authUrl

    private val _qrUri = MutableStateFlow<String?>(null)
    val qrUri: StateFlow<String?> = _qrUri.asStateFlow()

    private var qrJob: Job? = null

    /**
     * The active QR-flow Nip46Client. Tracked here so [cancelQrSession] can
     * tear its WebSocket connections down — the durable response subscription
     * stays open until disconnect, so simply cancelling [qrJob] is not enough.
     */
    private var qrClient: Nip46Client? = null

    // Relays used to seed the nostrconnect:// QR. Starts from the user's saved
    // list (if any) or the defaults; editable in the QR screen and persisted so
    // a flaky default relay can be replaced once and remembered.
    private val _nostrConnectRelays =
        MutableStateFlow(SecureStorage.getNostrConnectRelays() ?: repo.defaultNostrConnectRelays)
    val nostrConnectRelays: StateFlow<List<String>> = _nostrConnectRelays.asStateFlow()

    /** Update and persist the nostrconnect relays. The QR is regenerated by the
     * caller restarting the session (which reads the new list). */
    fun setNostrConnectRelays(relays: List<String>) {
        val cleaned = relays.map { it.trim() }.filter { it.isNotEmpty() }.distinct()
        if (cleaned.isEmpty()) return
        _nostrConnectRelays.value = cleaned
        SecureStorage.saveNostrConnectRelays(cleaned)
    }

    fun clearAuthUrl() = repo.clearAuthUrl()

    fun loginWithPrivateKey(
        privKey: String,
        pubKey: String,
        isNewIdentity: Boolean = false,
        ncryptsec: String? = null,
        onResult: (Result<Unit>) -> Unit,
    ) {
        viewModelScope.launch {
            onResult(repo.loginSuspend(privKey, pubKey, isNewIdentity, ncryptsec).toKotlinResult())
        }
    }

    /** True when the input is a NIP-49 encrypted key; the UIs ask for [loginWithPrivateKeyInput]'s password. */
    fun isEncryptedKeyInput(input: String): Boolean = Nip49.isEncryptedKey(input)

    /** True for a plain (hex / nsec) key — the UIs offer the protect-with-password option for these. */
    fun isPlainKeyInput(input: String): Boolean = isValidKeyInput(input) && !Nip49.isEncryptedKey(input)

    /** Fresh private key from the platform CSPRNG (the generate flow; not kotlin.random). */
    fun generateNewKeyHex(): String = Crypto.generatePrivateKey().toHexString()

    /** npub + nsec for displaying a key backup; null when the hex is invalid. */
    fun deriveBech32Keys(hexOrNsec: String): Pair<String, String>? {
        val hex = parsePrivateKeyHex(hexOrNsec) ?: return null
        return try {
            Nip19.encodeNpub(KeyPair.fromPrivateKeyHex(hex).publicKeyHex) to Nip19.encodeNsec(hex)
        } catch (e: Throwable) {
            null
        }
    }

    /**
     * Login with a plain (hex / nsec) key in password-protected mode: the key is
     * wrapped as an ncryptsec (NIP-49, scrypt on the Default dispatcher), only the
     * encrypted form is persisted, and the next session restore asks the password
     * via [pendingUnlock].
     */
    fun loginProtected(
        input: String,
        password: String,
        isNewIdentity: Boolean = false,
        onResult: (Result<Unit>) -> Unit,
    ) {
        val hex = parsePrivateKeyHex(input)
        if (hex == null) {
            onResult(Result.failure(IllegalArgumentException("Invalid private key")))
            return
        }
        viewModelScope.launch {
            val ncryptsec = withContext(Dispatchers.Default) { Nip49.encrypt(hex.hexToByteArray(), password) }
            loginWithHex(hex, isNewIdentity, ncryptsec, onResult)
        }
    }

    /** Account waiting for its NIP-49 password at startup (drives the unlock dialog). */
    val pendingUnlock: StateFlow<Account?> = repo.pendingUnlockAccount

    /** Dismiss the unlock dialog; the user falls back to the regular login screen. */
    fun dismissUnlock() = repo.clearPendingUnlock()

    /**
     * Decrypt the pending account's stored ncryptsec with [password] and finish the
     * session restore. Fails with "Wrong password or corrupted key" on a bad password.
     */
    fun unlockWithPassword(
        password: String,
        onResult: (Result<Unit>) -> Unit,
    ) {
        val account = repo.pendingUnlockAccount.value
        if (account == null) {
            onResult(Result.failure(IllegalStateException("No account to unlock")))
            return
        }
        val ncryptsec = SecureStorage.getEncryptedPrivateKeyFor(account.pubkey)
        if (ncryptsec == null) {
            onResult(Result.failure(IllegalStateException("No encrypted key stored")))
            return
        }
        loginWithPrivateKeyInput(ncryptsec, password, onResult = onResult)
    }

    /**
     * True when the input is a complete, well-formed key: 64-char hex, a decodable
     * nsec, or a structurally valid ncryptsec. The UIs gate the Login button on this
     * so partial or garbage input never produces an "Invalid private key" round trip.
     */
    fun isValidKeyInput(input: String): Boolean {
        val s = input.trim()
        return if (Nip49.isEncryptedKey(s)) Nip49.hasValidStructure(s) else parsePrivateKeyHex(s) != null
    }

    /**
     * Accepts a raw nsec, 64-char hex, or NIP-49 ncryptsec private key, derives the
     * public key, and logs in. ncryptsec requires [password]; scrypt runs on the
     * Default dispatcher because the default log_n = 16 costs real CPU and memory.
     * The parsing lives here (not per-UI) so Compose and web validate identically.
     */
    fun loginWithPrivateKeyInput(
        input: String,
        password: String? = null,
        isNewIdentity: Boolean = false,
        onResult: (Result<Unit>) -> Unit,
    ) {
        if (Nip49.isEncryptedKey(input)) {
            if (password.isNullOrEmpty()) {
                onResult(Result.failure(IllegalArgumentException("Enter the key password")))
                return
            }
            viewModelScope.launch {
                val trimmed = input.trim()
                val keyBytes = withContext(Dispatchers.Default) { Nip49.decrypt(trimmed, password) }
                if (keyBytes == null) {
                    onResult(Result.failure(IllegalArgumentException("Wrong password or corrupted key")))
                } else {
                    // Logging in with an ncryptsec keeps the account password-protected:
                    // only the encrypted key is persisted (unlock asked at next startup).
                    loginWithHex(keyBytes.toHexString(), isNewIdentity, ncryptsec = trimmed, onResult)
                }
            }
            return
        }
        val hex = parsePrivateKeyHex(input)
        if (hex == null) {
            onResult(Result.failure(IllegalArgumentException("Invalid private key")))
            return
        }
        loginWithHex(hex, isNewIdentity, ncryptsec = null, onResult)
    }

    private fun loginWithHex(
        hex: String,
        isNewIdentity: Boolean,
        ncryptsec: String?,
        onResult: (Result<Unit>) -> Unit,
    ) {
        val pub =
            try {
                KeyPair.fromPrivateKeyHex(hex).publicKeyHex
            } catch (e: Throwable) {
                onResult(Result.failure(IllegalArgumentException("Invalid private key")))
                return
            }
        loginWithPrivateKey(hex, pub, isNewIdentity, ncryptsec, onResult)
    }

    fun loginWithNip07(
        pubkey: String,
        onResult: (Result<Unit>) -> Unit,
    ) {
        viewModelScope.launch {
            onResult(repo.loginWithNip07(pubkey).toKotlinResult())
        }
    }

    fun loginWithNip07Extension(onResult: (Result<Unit>) -> Unit) {
        viewModelScope.launch {
            try {
                val pubkey = Nip07.getPublicKey() // platform call — can throw if extension unavailable
                onResult(repo.loginWithNip07(pubkey).toKotlinResult())
            } catch (c: CancellationException) {
                throw c
            } catch (e: Exception) {
                onResult(Result.failure(e))
            }
        }
    }

    fun loginWithBunker(
        url: String,
        onResult: (Result<Unit>) -> Unit,
    ) {
        viewModelScope.launch {
            onResult(repo.loginWithBunker(url).map { }.toKotlinResult())
        }
    }

    fun startQrSession(
        onConnected: () -> Unit,
        onError: (String?) -> Unit,
    ) {
        qrJob?.cancel()
        qrClient?.disconnect()
        qrClient = null
        _qrUri.value = null
        qrJob =
            viewModelScope.launch {
                try {
                    val (uri, client) = repo.createNostrConnectSession(_nostrConnectRelays.value)
                    qrClient = client
                    _qrUri.value = uri
                    repo.completeNostrConnectLogin(client)
                    qrClient = null
                    onConnected()
                } catch (c: CancellationException) {
                    // Scope/job cancelled (screen left, Try Again, relay re-apply): tear the
                    // socket down and propagate — never report it as a connection failure.
                    qrClient?.disconnect()
                    qrClient = null
                    throw c
                } catch (e: Exception) {
                    qrClient?.disconnect()
                    qrClient = null
                    onError("Connection failed: ${e.message}")
                }
            }
    }

    fun cancelQrSession() {
        qrJob?.cancel()
        qrClient?.disconnect()
        qrClient = null
        _qrUri.value = null
    }

    override fun onCleared() {
        super.onCleared()
        qrJob?.cancel()
        qrClient?.disconnect()
        qrClient = null
    }

    private companion object {
        const val HEX_CHARS = "0123456789abcdefABCDEF"

        /** Accepts an nsec or a 64-char hex private key; returns the hex, or null if invalid. */
        fun parsePrivateKeyHex(input: String): String? {
            val s = input.trim()
            return when {
                s.startsWith("nsec1") -> (Nip19.decode(s) as? Nip19.Entity.Nsec)?.privkey
                s.length == 64 && s.all { it in HEX_CHARS } -> s.lowercase()
                else -> null
            }
        }
    }
}
