package org.nostr.nostrord.ui.components.emoji

data class EmojiEntry(
    val emoji: String,
    val name: String
)

object EmojiData {
    val byGroup: Map<EmojiGroup, List<EmojiEntry>> by lazy {
        mapOf(
            EmojiGroup.SMILEYS to SMILEYS,
            EmojiGroup.PEOPLE to PEOPLE,
            EmojiGroup.NATURE to NATURE,
            EmojiGroup.FOOD to FOOD,
            EmojiGroup.TRAVEL to TRAVEL,
            EmojiGroup.ACTIVITIES to ACTIVITIES,
            EmojiGroup.OBJECTS to OBJECTS,
            EmojiGroup.SYMBOLS to SYMBOLS,
            EmojiGroup.FLAGS to FLAGS,
        )
    }
}

// Smileys & Emotion
private val SMILEYS = listOf(
    EmojiEntry("😀", "grinning face"),
    EmojiEntry("😃", "grinning face with big eyes"),
    EmojiEntry("😄", "grinning face with smiling eyes"),
    EmojiEntry("😁", "beaming face with smiling eyes"),
    EmojiEntry("😆", "grinning squinting face"),
    EmojiEntry("😅", "grinning face with sweat"),
    EmojiEntry("🤣", "rolling on the floor laughing"),
    EmojiEntry("😂", "face with tears of joy"),
    EmojiEntry("🙂", "slightly smiling face"),
    EmojiEntry("🙃", "upside-down face"),
    EmojiEntry("😉", "winking face"),
    EmojiEntry("😊", "smiling face with smiling eyes"),
    EmojiEntry("😇", "smiling face with halo"),
    EmojiEntry("🥰", "smiling face with hearts"),
    EmojiEntry("😍", "smiling face with heart-eyes"),
    EmojiEntry("🤩", "star-struck"),
    EmojiEntry("😘", "face blowing a kiss"),
    EmojiEntry("😗", "kissing face"),
    EmojiEntry("😚", "kissing face with closed eyes"),
    EmojiEntry("😙", "kissing face with smiling eyes"),
    EmojiEntry("🥲", "smiling face with tear"),
    EmojiEntry("😋", "face savoring food"),
    EmojiEntry("😛", "face with tongue"),
    EmojiEntry("😜", "winking face with tongue"),
    EmojiEntry("🤪", "zany face"),
    EmojiEntry("😝", "squinting face with tongue"),
    EmojiEntry("🤑", "money-mouth face"),
    EmojiEntry("🤗", "hugging face"),
    EmojiEntry("🤭", "face with hand over mouth"),
    EmojiEntry("🤫", "shushing face"),
    EmojiEntry("🤔", "thinking face"),
    EmojiEntry("🫡", "saluting face"),
    EmojiEntry("🤐", "zipper-mouth face"),
    EmojiEntry("🤨", "face with raised eyebrow"),
    EmojiEntry("😐", "neutral face"),
    EmojiEntry("😑", "expressionless face"),
    EmojiEntry("😶", "face without mouth"),
    EmojiEntry("🫥", "dotted line face"),
    EmojiEntry("😏", "smirking face"),
    EmojiEntry("😒", "unamused face"),
    EmojiEntry("🙄", "face with rolling eyes"),
    EmojiEntry("😬", "grimacing face"),
    EmojiEntry("🫨", "shaking face"),
    EmojiEntry("😮‍💨", "face exhaling"),
    EmojiEntry("🤥", "lying face"),
    EmojiEntry("😌", "relieved face"),
    EmojiEntry("😔", "pensive face"),
    EmojiEntry("😪", "sleepy face"),
    EmojiEntry("🤤", "drooling face"),
    EmojiEntry("😴", "sleeping face"),
    EmojiEntry("😷", "face with medical mask"),
    EmojiEntry("🤒", "face with thermometer"),
    EmojiEntry("🤕", "face with head-bandage"),
    EmojiEntry("🤢", "nauseated face"),
    EmojiEntry("🤮", "face vomiting"),
    EmojiEntry("🤧", "sneezing face"),
    EmojiEntry("🥵", "hot face"),
    EmojiEntry("🥶", "cold face"),
    EmojiEntry("🥴", "woozy face"),
    EmojiEntry("😵", "face with crossed-out eyes"),
    EmojiEntry("🤯", "exploding head"),
    EmojiEntry("🤠", "cowboy hat face"),
    EmojiEntry("🥳", "partying face"),
    EmojiEntry("🥸", "disguised face"),
    EmojiEntry("😎", "smiling face with sunglasses"),
    EmojiEntry("🤓", "nerd face"),
    EmojiEntry("🧐", "face with monocle"),
    EmojiEntry("😕", "confused face"),
    EmojiEntry("🫤", "face with diagonal mouth"),
    EmojiEntry("😟", "worried face"),
    EmojiEntry("🙁", "slightly frowning face"),
    EmojiEntry("😮", "face with open mouth"),
    EmojiEntry("😯", "hushed face"),
    EmojiEntry("😲", "astonished face"),
    EmojiEntry("😳", "flushed face"),
    EmojiEntry("🥺", "pleading face"),
    EmojiEntry("🥹", "face holding back tears"),
    EmojiEntry("😦", "frowning face with open mouth"),
    EmojiEntry("😧", "anguished face"),
    EmojiEntry("😨", "fearful face"),
    EmojiEntry("😰", "anxious face with sweat"),
    EmojiEntry("😥", "sad but relieved face"),
    EmojiEntry("😢", "crying face"),
    EmojiEntry("😭", "loudly crying face"),
    EmojiEntry("😱", "face screaming in fear"),
    EmojiEntry("😖", "confounded face"),
    EmojiEntry("😣", "persevering face"),
    EmojiEntry("😞", "disappointed face"),
    EmojiEntry("😓", "downcast face with sweat"),
    EmojiEntry("😩", "weary face"),
    EmojiEntry("😫", "tired face"),
    EmojiEntry("🥱", "yawning face"),
    EmojiEntry("😤", "face with steam from nose"),
    EmojiEntry("😡", "pouting face"),
    EmojiEntry("😠", "angry face"),
    EmojiEntry("🤬", "face with symbols on mouth"),
    EmojiEntry("😈", "smiling face with horns"),
    EmojiEntry("👿", "angry face with horns"),
    EmojiEntry("💀", "skull"),
    EmojiEntry("☠️", "skull and crossbones"),
    EmojiEntry("💩", "pile of poo"),
    EmojiEntry("🤡", "clown face"),
    EmojiEntry("👹", "ogre"),
    EmojiEntry("👺", "goblin"),
    EmojiEntry("👻", "ghost"),
    EmojiEntry("👽", "alien"),
    EmojiEntry("👾", "alien monster"),
    EmojiEntry("🤖", "robot"),
    EmojiEntry("😺", "grinning cat"),
    EmojiEntry("😸", "grinning cat with smiling eyes"),
    EmojiEntry("😹", "cat with tears of joy"),
    EmojiEntry("😻", "smiling cat with heart-eyes"),
    EmojiEntry("😼", "cat with wry smile"),
    EmojiEntry("😽", "kissing cat"),
    EmojiEntry("🙀", "weary cat"),
    EmojiEntry("😿", "crying cat"),
    EmojiEntry("😾", "pouting cat"),
    EmojiEntry("🫶", "heart hands"),
    EmojiEntry("❤️", "red heart"),
    EmojiEntry("🧡", "orange heart"),
    EmojiEntry("💛", "yellow heart"),
    EmojiEntry("💚", "green heart"),
    EmojiEntry("💙", "blue heart"),
    EmojiEntry("💜", "purple heart"),
    EmojiEntry("🖤", "black heart"),
    EmojiEntry("🤍", "white heart"),
    EmojiEntry("🤎", "brown heart"),
    EmojiEntry("💔", "broken heart"),
    EmojiEntry("❣️", "heart exclamation"),
    EmojiEntry("💕", "two hearts"),
    EmojiEntry("💞", "revolving hearts"),
    EmojiEntry("💓", "beating heart"),
    EmojiEntry("💗", "growing heart"),
    EmojiEntry("💖", "sparkling heart"),
    EmojiEntry("💘", "heart with arrow"),
    EmojiEntry("💝", "heart with ribbon"),
    EmojiEntry("💟", "heart decoration"),
    EmojiEntry("💯", "hundred points"),
    EmojiEntry("💢", "anger symbol"),
    EmojiEntry("💥", "collision"),
    EmojiEntry("💫", "dizzy"),
    EmojiEntry("💦", "sweat droplets"),
    EmojiEntry("💨", "dashing away"),
    EmojiEntry("🕳️", "hole"),
    EmojiEntry("💬", "speech balloon"),
    EmojiEntry("💭", "thought balloon"),
    EmojiEntry("💤", "zzz"),
)

// People & Body
private val PEOPLE = listOf(
    EmojiEntry("👋", "waving hand"),
    EmojiEntry("🤚", "raised back of hand"),
    EmojiEntry("🖐️", "hand with fingers splayed"),
    EmojiEntry("✋", "raised hand"),
    EmojiEntry("🖖", "vulcan salute"),
    EmojiEntry("🫱", "rightwards hand"),
    EmojiEntry("🫲", "leftwards hand"),
    EmojiEntry("🫳", "palm down hand"),
    EmojiEntry("🫴", "palm up hand"),
    EmojiEntry("👌", "OK hand"),
    EmojiEntry("🤌", "pinched fingers"),
    EmojiEntry("🤏", "pinching hand"),
    EmojiEntry("✌️", "victory hand"),
    EmojiEntry("🤞", "crossed fingers"),
    EmojiEntry("🫰", "hand with index finger and thumb crossed"),
    EmojiEntry("🤟", "love-you gesture"),
    EmojiEntry("🤘", "sign of the horns"),
    EmojiEntry("🤙", "call me hand"),
    EmojiEntry("👈", "backhand index pointing left"),
    EmojiEntry("👉", "backhand index pointing right"),
    EmojiEntry("👆", "backhand index pointing up"),
    EmojiEntry("🖕", "middle finger"),
    EmojiEntry("👇", "backhand index pointing down"),
    EmojiEntry("☝️", "index pointing up"),
    EmojiEntry("🫵", "index pointing at the viewer"),
    EmojiEntry("👍", "thumbs up"),
    EmojiEntry("👎", "thumbs down"),
    EmojiEntry("✊", "raised fist"),
    EmojiEntry("👊", "oncoming fist"),
    EmojiEntry("🤛", "left-facing fist"),
    EmojiEntry("🤜", "right-facing fist"),
    EmojiEntry("👏", "clapping hands"),
    EmojiEntry("🙌", "raising hands"),
    EmojiEntry("🫶", "heart hands"),
    EmojiEntry("👐", "open hands"),
    EmojiEntry("🤲", "palms up together"),
    EmojiEntry("🤝", "handshake"),
    EmojiEntry("🙏", "folded hands"),
    EmojiEntry("✍️", "writing hand"),
    EmojiEntry("💅", "nail polish"),
    EmojiEntry("🤳", "selfie"),
    EmojiEntry("💪", "flexed biceps"),
    EmojiEntry("🦾", "mechanical arm"),
    EmojiEntry("🦿", "mechanical leg"),
    EmojiEntry("🦵", "leg"),
    EmojiEntry("🦶", "foot"),
    EmojiEntry("👂", "ear"),
    EmojiEntry("🦻", "ear with hearing aid"),
    EmojiEntry("👃", "nose"),
    EmojiEntry("🧠", "brain"),
    EmojiEntry("👀", "eyes"),
    EmojiEntry("👁️", "eye"),
    EmojiEntry("👅", "tongue"),
    EmojiEntry("👄", "mouth"),
    EmojiEntry("👶", "baby"),
    EmojiEntry("🧒", "child"),
    EmojiEntry("👦", "boy"),
    EmojiEntry("👧", "girl"),
    EmojiEntry("🧑", "person"),
    EmojiEntry("👱", "person blond hair"),
    EmojiEntry("👨", "man"),
    EmojiEntry("🧔", "person beard"),
    EmojiEntry("👩", "woman"),
    EmojiEntry("🧓", "older person"),
    EmojiEntry("👴", "old man"),
    EmojiEntry("👵", "old woman"),
    EmojiEntry("🙍", "person frowning"),
    EmojiEntry("🙎", "person pouting"),
    EmojiEntry("🙅", "person gesturing NO"),
    EmojiEntry("🙆", "person gesturing OK"),
    EmojiEntry("💁", "person tipping hand"),
    EmojiEntry("🙋", "person raising hand"),
    EmojiEntry("🧏", "deaf person"),
    EmojiEntry("🙇", "person bowing"),
    EmojiEntry("🤦", "person facepalming"),
    EmojiEntry("🤷", "person shrugging"),
    EmojiEntry("👮", "police officer"),
    EmojiEntry("🕵️", "detective"),
    EmojiEntry("💂", "guard"),
    EmojiEntry("🥷", "ninja"),
    EmojiEntry("👷", "construction worker"),
    EmojiEntry("🫅", "person with crown"),
    EmojiEntry("🤴", "prince"),
    EmojiEntry("👸", "princess"),
    EmojiEntry("👳", "person wearing turban"),
    EmojiEntry("👲", "person with skullcap"),
    EmojiEntry("🧕", "woman with headscarf"),
    EmojiEntry("🤵", "person in tuxedo"),
    EmojiEntry("👰", "person with veil"),
    EmojiEntry("🤰", "pregnant woman"),
    EmojiEntry("🫃", "pregnant man"),
    EmojiEntry("🫄", "pregnant person"),
    EmojiEntry("👼", "baby angel"),
    EmojiEntry("🎅", "Santa Claus"),
    EmojiEntry("🤶", "Mrs. Claus"),
    EmojiEntry("🦸", "superhero"),
    EmojiEntry("🦹", "supervillain"),
    EmojiEntry("🧙", "mage"),
    EmojiEntry("🧚", "fairy"),
    EmojiEntry("🧛", "vampire"),
    EmojiEntry("🧜", "merperson"),
    EmojiEntry("🧝", "elf"),
    EmojiEntry("🧞", "genie"),
    EmojiEntry("🧟", "zombie"),
    EmojiEntry("🧌", "troll"),
    EmojiEntry("💆", "person getting massage"),
    EmojiEntry("💇", "person getting haircut"),
    EmojiEntry("🚶", "person walking"),
    EmojiEntry("🧍", "person standing"),
    EmojiEntry("🧎", "person kneeling"),
    EmojiEntry("🏃", "person running"),
    EmojiEntry("💃", "woman dancing"),
    EmojiEntry("🕺", "man dancing"),
    EmojiEntry("👯", "people with bunny ears"),
    EmojiEntry("🧖", "person in steamy room"),
    EmojiEntry("🧗", "person climbing"),
    EmojiEntry("🤺", "person fencing"),
    EmojiEntry("🏇", "horse racing"),
    EmojiEntry("⛷️", "skier"),
    EmojiEntry("🏂", "snowboarder"),
    EmojiEntry("🏌️", "person golfing"),
    EmojiEntry("🏄", "person surfing"),
    EmojiEntry("🚣", "person rowing boat"),
    EmojiEntry("🏊", "person swimming"),
    EmojiEntry("⛹️", "person bouncing ball"),
    EmojiEntry("🏋️", "person lifting weights"),
    EmojiEntry("🚴", "person biking"),
    EmojiEntry("🚵", "person mountain biking"),
    EmojiEntry("🤸", "person cartwheeling"),
    EmojiEntry("🤼", "people wrestling"),
    EmojiEntry("🤽", "person playing water polo"),
    EmojiEntry("🤾", "person playing handball"),
    EmojiEntry("🤹", "person juggling"),
    EmojiEntry("🧘", "person in lotus position"),
    EmojiEntry("👫", "woman and man holding hands"),
    EmojiEntry("👬", "men holding hands"),
    EmojiEntry("👭", "women holding hands"),
    EmojiEntry("💏", "kiss"),
    EmojiEntry("💑", "couple with heart"),
    EmojiEntry("👪", "family"),
    EmojiEntry("🗣️", "speaking head"),
    EmojiEntry("👤", "bust in silhouette"),
    EmojiEntry("👥", "busts in silhouette"),
    EmojiEntry("🫂", "people hugging"),
    EmojiEntry("👣", "footprints"),
)

// Animals & Nature
private val NATURE = listOf(
    EmojiEntry("🐵", "monkey face"),
    EmojiEntry("🐒", "monkey"),
    EmojiEntry("🦍", "gorilla"),
    EmojiEntry("🦧", "orangutan"),
    EmojiEntry("🐶", "dog face"),
    EmojiEntry("🐕", "dog"),
    EmojiEntry("🦮", "guide dog"),
    EmojiEntry("🐩", "poodle"),
    EmojiEntry("🐺", "wolf"),
    EmojiEntry("🦊", "fox"),
    EmojiEntry("🦝", "raccoon"),
    EmojiEntry("🐱", "cat face"),
    EmojiEntry("🐈", "cat"),
    EmojiEntry("🦁", "lion"),
    EmojiEntry("🐯", "tiger face"),
    EmojiEntry("🐅", "tiger"),
    EmojiEntry("🐆", "leopard"),
    EmojiEntry("🐴", "horse face"),
    EmojiEntry("🐎", "horse"),
    EmojiEntry("🦄", "unicorn"),
    EmojiEntry("🦓", "zebra"),
    EmojiEntry("🦌", "deer"),
    EmojiEntry("🦬", "bison"),
    EmojiEntry("🐮", "cow face"),
    EmojiEntry("🐂", "ox"),
    EmojiEntry("🐃", "water buffalo"),
    EmojiEntry("🐄", "cow"),
    EmojiEntry("🐷", "pig face"),
    EmojiEntry("🐖", "pig"),
    EmojiEntry("🐗", "boar"),
    EmojiEntry("🐽", "pig nose"),
    EmojiEntry("🐏", "ram"),
    EmojiEntry("🐑", "ewe"),
    EmojiEntry("🐐", "goat"),
    EmojiEntry("🐪", "camel"),
    EmojiEntry("🐫", "two-hump camel"),
    EmojiEntry("🦙", "llama"),
    EmojiEntry("🦒", "giraffe"),
    EmojiEntry("🐘", "elephant"),
    EmojiEntry("🦣", "mammoth"),
    EmojiEntry("🦏", "rhinoceros"),
    EmojiEntry("🦛", "hippopotamus"),
    EmojiEntry("🐭", "mouse face"),
    EmojiEntry("🐁", "mouse"),
    EmojiEntry("🐀", "rat"),
    EmojiEntry("🐹", "hamster"),
    EmojiEntry("🐰", "rabbit face"),
    EmojiEntry("🐇", "rabbit"),
    EmojiEntry("🐿️", "chipmunk"),
    EmojiEntry("🦫", "beaver"),
    EmojiEntry("🦔", "hedgehog"),
    EmojiEntry("🦇", "bat"),
    EmojiEntry("🐻", "bear"),
    EmojiEntry("🐻‍❄️", "polar bear"),
    EmojiEntry("🐨", "koala"),
    EmojiEntry("🐼", "panda"),
    EmojiEntry("🦥", "sloth"),
    EmojiEntry("🦦", "otter"),
    EmojiEntry("🦨", "skunk"),
    EmojiEntry("🦘", "kangaroo"),
    EmojiEntry("🦡", "badger"),
    EmojiEntry("🐾", "paw prints"),
    EmojiEntry("🦃", "turkey"),
    EmojiEntry("🐔", "chicken"),
    EmojiEntry("🐓", "rooster"),
    EmojiEntry("🐣", "hatching chick"),
    EmojiEntry("🐤", "baby chick"),
    EmojiEntry("🐥", "front-facing baby chick"),
    EmojiEntry("🐦", "bird"),
    EmojiEntry("🐧", "penguin"),
    EmojiEntry("🕊️", "dove"),
    EmojiEntry("🦅", "eagle"),
    EmojiEntry("🦆", "duck"),
    EmojiEntry("🦢", "swan"),
    EmojiEntry("🦉", "owl"),
    EmojiEntry("🦤", "dodo"),
    EmojiEntry("🪶", "feather"),
    EmojiEntry("🦩", "flamingo"),
    EmojiEntry("🦚", "peacock"),
    EmojiEntry("🦜", "parrot"),
    EmojiEntry("🐸", "frog"),
    EmojiEntry("🐊", "crocodile"),
    EmojiEntry("🐢", "turtle"),
    EmojiEntry("🦎", "lizard"),
    EmojiEntry("🐍", "snake"),
    EmojiEntry("🐲", "dragon face"),
    EmojiEntry("🐉", "dragon"),
    EmojiEntry("🦕", "sauropod"),
    EmojiEntry("🦖", "t-rex"),
    EmojiEntry("🐳", "spouting whale"),
    EmojiEntry("🐋", "whale"),
    EmojiEntry("🐬", "dolphin"),
    EmojiEntry("🦭", "seal"),
    EmojiEntry("🐟", "fish"),
    EmojiEntry("🐠", "tropical fish"),
    EmojiEntry("🐡", "blowfish"),
    EmojiEntry("🦈", "shark"),
    EmojiEntry("🐙", "octopus"),
    EmojiEntry("🐚", "spiral shell"),
    EmojiEntry("🪸", "coral"),
    EmojiEntry("🐌", "snail"),
    EmojiEntry("🦋", "butterfly"),
    EmojiEntry("🐛", "bug"),
    EmojiEntry("🐜", "ant"),
    EmojiEntry("🐝", "honeybee"),
    EmojiEntry("🪲", "beetle"),
    EmojiEntry("🐞", "lady beetle"),
    EmojiEntry("🦗", "cricket"),
    EmojiEntry("🪳", "cockroach"),
    EmojiEntry("🕷️", "spider"),
    EmojiEntry("🕸️", "spider web"),
    EmojiEntry("🦂", "scorpion"),
    EmojiEntry("🦟", "mosquito"),
    EmojiEntry("🪰", "fly"),
    EmojiEntry("🪱", "worm"),
    EmojiEntry("🌸", "cherry blossom"),
    EmojiEntry("💐", "bouquet"),
    EmojiEntry("🏵️", "rosette"),
    EmojiEntry("🌹", "rose"),
    EmojiEntry("🥀", "wilted flower"),
    EmojiEntry("🌺", "hibiscus"),
    EmojiEntry("🌻", "sunflower"),
    EmojiEntry("🌼", "blossom"),
    EmojiEntry("🌷", "tulip"),
    EmojiEntry("🌱", "seedling"),
    EmojiEntry("🪴", "potted plant"),
    EmojiEntry("🌲", "evergreen tree"),
    EmojiEntry("🌳", "deciduous tree"),
    EmojiEntry("🌴", "palm tree"),
    EmojiEntry("🌵", "cactus"),
    EmojiEntry("🌾", "sheaf of rice"),
    EmojiEntry("🌿", "herb"),
    EmojiEntry("☘️", "shamrock"),
    EmojiEntry("🍀", "four leaf clover"),
    EmojiEntry("🍁", "maple leaf"),
    EmojiEntry("🍂", "fallen leaf"),
    EmojiEntry("🍃", "leaf fluttering in wind"),
    EmojiEntry("🪹", "empty nest"),
    EmojiEntry("🪺", "nest with eggs"),
    EmojiEntry("🍄", "mushroom"),
)

// Food & Drink
private val FOOD = listOf(
    EmojiEntry("🍇", "grapes"),
    EmojiEntry("🍈", "melon"),
    EmojiEntry("🍉", "watermelon"),
    EmojiEntry("🍊", "tangerine"),
    EmojiEntry("🍋", "lemon"),
    EmojiEntry("🍌", "banana"),
    EmojiEntry("🍍", "pineapple"),
    EmojiEntry("🥭", "mango"),
    EmojiEntry("🍎", "red apple"),
    EmojiEntry("🍏", "green apple"),
    EmojiEntry("🍐", "pear"),
    EmojiEntry("🍑", "peach"),
    EmojiEntry("🍒", "cherries"),
    EmojiEntry("🍓", "strawberry"),
    EmojiEntry("🫐", "blueberries"),
    EmojiEntry("🥝", "kiwi fruit"),
    EmojiEntry("🍅", "tomato"),
    EmojiEntry("🫒", "olive"),
    EmojiEntry("🥥", "coconut"),
    EmojiEntry("🥑", "avocado"),
    EmojiEntry("🍆", "eggplant"),
    EmojiEntry("🥔", "potato"),
    EmojiEntry("🥕", "carrot"),
    EmojiEntry("🌽", "ear of corn"),
    EmojiEntry("🌶️", "hot pepper"),
    EmojiEntry("🫑", "bell pepper"),
    EmojiEntry("🥒", "cucumber"),
    EmojiEntry("🥬", "leafy green"),
    EmojiEntry("🥦", "broccoli"),
    EmojiEntry("🧄", "garlic"),
    EmojiEntry("🧅", "onion"),
    EmojiEntry("🥜", "peanuts"),
    EmojiEntry("🫘", "beans"),
    EmojiEntry("🌰", "chestnut"),
    EmojiEntry("🍞", "bread"),
    EmojiEntry("🥐", "croissant"),
    EmojiEntry("🥖", "baguette bread"),
    EmojiEntry("🫓", "flatbread"),
    EmojiEntry("🥨", "pretzel"),
    EmojiEntry("🥯", "bagel"),
    EmojiEntry("🥞", "pancakes"),
    EmojiEntry("🧇", "waffle"),
    EmojiEntry("🧀", "cheese wedge"),
    EmojiEntry("🍖", "meat on bone"),
    EmojiEntry("🍗", "poultry leg"),
    EmojiEntry("🥩", "cut of meat"),
    EmojiEntry("🥓", "bacon"),
    EmojiEntry("🍔", "hamburger"),
    EmojiEntry("🍟", "french fries"),
    EmojiEntry("🍕", "pizza"),
    EmojiEntry("🌭", "hot dog"),
    EmojiEntry("🥪", "sandwich"),
    EmojiEntry("🌮", "taco"),
    EmojiEntry("🌯", "burrito"),
    EmojiEntry("🫔", "tamale"),
    EmojiEntry("🥙", "stuffed flatbread"),
    EmojiEntry("🧆", "falafel"),
    EmojiEntry("🥚", "egg"),
    EmojiEntry("🍳", "cooking"),
    EmojiEntry("🥘", "shallow pan of food"),
    EmojiEntry("🍲", "pot of food"),
    EmojiEntry("🫕", "fondue"),
    EmojiEntry("🥣", "bowl with spoon"),
    EmojiEntry("🥗", "green salad"),
    EmojiEntry("🍿", "popcorn"),
    EmojiEntry("🧈", "butter"),
    EmojiEntry("🧂", "salt"),
    EmojiEntry("🥫", "canned food"),
    EmojiEntry("🍱", "bento box"),
    EmojiEntry("🍘", "rice cracker"),
    EmojiEntry("🍙", "rice ball"),
    EmojiEntry("🍚", "cooked rice"),
    EmojiEntry("🍛", "curry rice"),
    EmojiEntry("🍜", "steaming bowl"),
    EmojiEntry("🍝", "spaghetti"),
    EmojiEntry("🍠", "roasted sweet potato"),
    EmojiEntry("🍢", "oden"),
    EmojiEntry("🍣", "sushi"),
    EmojiEntry("🍤", "fried shrimp"),
    EmojiEntry("🍥", "fish cake with swirl"),
    EmojiEntry("🥮", "moon cake"),
    EmojiEntry("🍡", "dango"),
    EmojiEntry("🥟", "dumpling"),
    EmojiEntry("🥠", "fortune cookie"),
    EmojiEntry("🥡", "takeout box"),
    EmojiEntry("🦀", "crab"),
    EmojiEntry("🦞", "lobster"),
    EmojiEntry("🦐", "shrimp"),
    EmojiEntry("🦑", "squid"),
    EmojiEntry("🦪", "oyster"),
    EmojiEntry("🍦", "soft ice cream"),
    EmojiEntry("🍧", "shaved ice"),
    EmojiEntry("🍨", "ice cream"),
    EmojiEntry("🍩", "doughnut"),
    EmojiEntry("🍪", "cookie"),
    EmojiEntry("🎂", "birthday cake"),
    EmojiEntry("🍰", "shortcake"),
    EmojiEntry("🧁", "cupcake"),
    EmojiEntry("🥧", "pie"),
    EmojiEntry("🍫", "chocolate bar"),
    EmojiEntry("🍬", "candy"),
    EmojiEntry("🍭", "lollipop"),
    EmojiEntry("🍮", "custard"),
    EmojiEntry("🍯", "honey pot"),
    EmojiEntry("🍼", "baby bottle"),
    EmojiEntry("🥛", "glass of milk"),
    EmojiEntry("☕", "hot beverage"),
    EmojiEntry("🫖", "teapot"),
    EmojiEntry("🍵", "teacup without handle"),
    EmojiEntry("🍶", "sake"),
    EmojiEntry("🍾", "bottle with popping cork"),
    EmojiEntry("🍷", "wine glass"),
    EmojiEntry("🍸", "cocktail glass"),
    EmojiEntry("🍹", "tropical drink"),
    EmojiEntry("🍺", "beer mug"),
    EmojiEntry("🍻", "clinking beer mugs"),
    EmojiEntry("🥂", "clinking glasses"),
    EmojiEntry("🥃", "tumbler glass"),
    EmojiEntry("🫗", "pouring liquid"),
    EmojiEntry("🥤", "cup with straw"),
    EmojiEntry("🧋", "bubble tea"),
    EmojiEntry("🧃", "beverage box"),
    EmojiEntry("🧉", "mate"),
    EmojiEntry("🧊", "ice"),
    EmojiEntry("🥢", "chopsticks"),
    EmojiEntry("🍽️", "fork and knife with plate"),
    EmojiEntry("🍴", "fork and knife"),
    EmojiEntry("🥄", "spoon"),
)

// Travel & Places
private val TRAVEL = listOf(
    EmojiEntry("🌍", "globe showing Europe-Africa"),
    EmojiEntry("🌎", "globe showing Americas"),
    EmojiEntry("🌏", "globe showing Asia-Australia"),
    EmojiEntry("🗺️", "world map"),
    EmojiEntry("🏠", "house"),
    EmojiEntry("🏡", "house with garden"),
    EmojiEntry("🏢", "office building"),
    EmojiEntry("🏣", "Japanese post office"),
    EmojiEntry("🏥", "hospital"),
    EmojiEntry("🏦", "bank"),
    EmojiEntry("🏨", "hotel"),
    EmojiEntry("🏩", "love hotel"),
    EmojiEntry("🏪", "convenience store"),
    EmojiEntry("🏫", "school"),
    EmojiEntry("🏬", "department store"),
    EmojiEntry("🏭", "factory"),
    EmojiEntry("🏯", "Japanese castle"),
    EmojiEntry("🏰", "castle"),
    EmojiEntry("💒", "wedding"),
    EmojiEntry("🗼", "Tokyo tower"),
    EmojiEntry("🗽", "Statue of Liberty"),
    EmojiEntry("⛪", "church"),
    EmojiEntry("🕌", "mosque"),
    EmojiEntry("🛕", "hindu temple"),
    EmojiEntry("🕍", "synagogue"),
    EmojiEntry("⛩️", "shinto shrine"),
    EmojiEntry("🕋", "kaaba"),
    EmojiEntry("⛲", "fountain"),
    EmojiEntry("⛺", "tent"),
    EmojiEntry("🌁", "foggy"),
    EmojiEntry("🌃", "night with stars"),
    EmojiEntry("🏙️", "cityscape"),
    EmojiEntry("🌄", "sunrise over mountains"),
    EmojiEntry("🌅", "sunrise"),
    EmojiEntry("🌆", "cityscape at dusk"),
    EmojiEntry("🌇", "sunset"),
    EmojiEntry("🌉", "bridge at night"),
    EmojiEntry("🎠", "carousel horse"),
    EmojiEntry("🛝", "playground slide"),
    EmojiEntry("🎡", "ferris wheel"),
    EmojiEntry("🎢", "roller coaster"),
    EmojiEntry("🚂", "locomotive"),
    EmojiEntry("🚃", "railway car"),
    EmojiEntry("🚄", "high-speed train"),
    EmojiEntry("🚅", "bullet train"),
    EmojiEntry("🚆", "train"),
    EmojiEntry("🚇", "metro"),
    EmojiEntry("🚈", "light rail"),
    EmojiEntry("🚉", "station"),
    EmojiEntry("🚌", "bus"),
    EmojiEntry("🚍", "oncoming bus"),
    EmojiEntry("🚎", "trolleybus"),
    EmojiEntry("🚐", "minibus"),
    EmojiEntry("🚑", "ambulance"),
    EmojiEntry("🚒", "fire engine"),
    EmojiEntry("🚓", "police car"),
    EmojiEntry("🚔", "oncoming police car"),
    EmojiEntry("🚕", "taxi"),
    EmojiEntry("🚗", "automobile"),
    EmojiEntry("🚙", "sport utility vehicle"),
    EmojiEntry("🛻", "pickup truck"),
    EmojiEntry("🚚", "delivery truck"),
    EmojiEntry("🚛", "articulated lorry"),
    EmojiEntry("🚜", "tractor"),
    EmojiEntry("🏎️", "racing car"),
    EmojiEntry("🏍️", "motorcycle"),
    EmojiEntry("🛵", "motor scooter"),
    EmojiEntry("🛺", "auto rickshaw"),
    EmojiEntry("🚲", "bicycle"),
    EmojiEntry("🛴", "kick scooter"),
    EmojiEntry("🚏", "bus stop"),
    EmojiEntry("🛣️", "motorway"),
    EmojiEntry("⛽", "fuel pump"),
    EmojiEntry("🚨", "police car light"),
    EmojiEntry("🚥", "horizontal traffic light"),
    EmojiEntry("🚦", "vertical traffic light"),
    EmojiEntry("⚓", "anchor"),
    EmojiEntry("🛟", "ring buoy"),
    EmojiEntry("⛵", "sailboat"),
    EmojiEntry("🚤", "speedboat"),
    EmojiEntry("🛳️", "passenger ship"),
    EmojiEntry("⛴️", "ferry"),
    EmojiEntry("🛥️", "motor boat"),
    EmojiEntry("🚢", "ship"),
    EmojiEntry("✈️", "airplane"),
    EmojiEntry("🛩️", "small airplane"),
    EmojiEntry("🛫", "airplane departure"),
    EmojiEntry("🛬", "airplane arrival"),
    EmojiEntry("🪂", "parachute"),
    EmojiEntry("💺", "seat"),
    EmojiEntry("🚁", "helicopter"),
    EmojiEntry("🚀", "rocket"),
    EmojiEntry("🛸", "flying saucer"),
    EmojiEntry("🌙", "crescent moon"),
    EmojiEntry("🌛", "first quarter moon face"),
    EmojiEntry("🌜", "last quarter moon face"),
    EmojiEntry("🌝", "full moon face"),
    EmojiEntry("🌞", "sun with face"),
    EmojiEntry("⭐", "star"),
    EmojiEntry("🌟", "glowing star"),
    EmojiEntry("🌠", "shooting star"),
    EmojiEntry("☁️", "cloud"),
    EmojiEntry("⛅", "sun behind cloud"),
    EmojiEntry("🌤️", "sun behind small cloud"),
    EmojiEntry("🌥️", "sun behind large cloud"),
    EmojiEntry("🌦️", "sun behind rain cloud"),
    EmojiEntry("🌧️", "cloud with rain"),
    EmojiEntry("⛈️", "cloud with lightning and rain"),
    EmojiEntry("🌩️", "cloud with lightning"),
    EmojiEntry("🌪️", "tornado"),
    EmojiEntry("🌫️", "fog"),
    EmojiEntry("🌬️", "wind face"),
    EmojiEntry("🌈", "rainbow"),
    EmojiEntry("☀️", "sun"),
    EmojiEntry("🌡️", "thermometer"),
    EmojiEntry("🔥", "fire"),
    EmojiEntry("💧", "droplet"),
    EmojiEntry("🌊", "water wave"),
)

// Activities
private val ACTIVITIES = listOf(
    EmojiEntry("🎃", "jack-o-lantern"),
    EmojiEntry("🎄", "Christmas tree"),
    EmojiEntry("🎆", "fireworks"),
    EmojiEntry("🎇", "sparkler"),
    EmojiEntry("🧨", "firecracker"),
    EmojiEntry("✨", "sparkles"),
    EmojiEntry("🎈", "balloon"),
    EmojiEntry("🎉", "party popper"),
    EmojiEntry("🎊", "confetti ball"),
    EmojiEntry("🎋", "tanabata tree"),
    EmojiEntry("🎍", "pine decoration"),
    EmojiEntry("🎎", "Japanese dolls"),
    EmojiEntry("🎏", "carp streamer"),
    EmojiEntry("🎐", "wind chime"),
    EmojiEntry("🎑", "moon viewing ceremony"),
    EmojiEntry("🧧", "red envelope"),
    EmojiEntry("🎀", "ribbon"),
    EmojiEntry("🎁", "wrapped gift"),
    EmojiEntry("🎗️", "reminder ribbon"),
    EmojiEntry("🎟️", "admission tickets"),
    EmojiEntry("🎫", "ticket"),
    EmojiEntry("🎖️", "military medal"),
    EmojiEntry("🏆", "trophy"),
    EmojiEntry("🏅", "sports medal"),
    EmojiEntry("🥇", "1st place medal"),
    EmojiEntry("🥈", "2nd place medal"),
    EmojiEntry("🥉", "3rd place medal"),
    EmojiEntry("⚽", "soccer ball"),
    EmojiEntry("⚾", "baseball"),
    EmojiEntry("🥎", "softball"),
    EmojiEntry("🏀", "basketball"),
    EmojiEntry("🏐", "volleyball"),
    EmojiEntry("🏈", "american football"),
    EmojiEntry("🏉", "rugby football"),
    EmojiEntry("🎾", "tennis"),
    EmojiEntry("🥏", "flying disc"),
    EmojiEntry("🎳", "bowling"),
    EmojiEntry("🏏", "cricket game"),
    EmojiEntry("🏑", "field hockey"),
    EmojiEntry("🏒", "ice hockey"),
    EmojiEntry("🥍", "lacrosse"),
    EmojiEntry("🏓", "ping pong"),
    EmojiEntry("🏸", "badminton"),
    EmojiEntry("🥊", "boxing glove"),
    EmojiEntry("🥋", "martial arts uniform"),
    EmojiEntry("🥅", "goal net"),
    EmojiEntry("⛳", "flag in hole"),
    EmojiEntry("⛸️", "ice skate"),
    EmojiEntry("🎣", "fishing pole"),
    EmojiEntry("🤿", "diving mask"),
    EmojiEntry("🎽", "running shirt"),
    EmojiEntry("🎿", "skis"),
    EmojiEntry("🛷", "sled"),
    EmojiEntry("🥌", "curling stone"),
    EmojiEntry("🎯", "bullseye"),
    EmojiEntry("🪀", "yo-yo"),
    EmojiEntry("🪁", "kite"),
    EmojiEntry("🎱", "pool 8 ball"),
    EmojiEntry("🔮", "crystal ball"),
    EmojiEntry("🪄", "magic wand"),
    EmojiEntry("🎮", "video game"),
    EmojiEntry("🕹️", "joystick"),
    EmojiEntry("🎰", "slot machine"),
    EmojiEntry("🎲", "game die"),
    EmojiEntry("🧩", "puzzle piece"),
    EmojiEntry("🧸", "teddy bear"),
    EmojiEntry("🪅", "pinata"),
    EmojiEntry("🪩", "mirror ball"),
    EmojiEntry("🪆", "nesting dolls"),
    EmojiEntry("♠️", "spade suit"),
    EmojiEntry("♥️", "heart suit"),
    EmojiEntry("♦️", "diamond suit"),
    EmojiEntry("♣️", "club suit"),
    EmojiEntry("♟️", "chess pawn"),
    EmojiEntry("🃏", "joker"),
    EmojiEntry("🀄", "mahjong red dragon"),
    EmojiEntry("🎴", "flower playing cards"),
    EmojiEntry("🎭", "performing arts"),
    EmojiEntry("🖼️", "framed picture"),
    EmojiEntry("🎨", "artist palette"),
    EmojiEntry("🧵", "thread"),
    EmojiEntry("🪡", "sewing needle"),
    EmojiEntry("🧶", "yarn"),
    EmojiEntry("🪢", "knot"),
)

// Objects
private val OBJECTS = listOf(
    EmojiEntry("👓", "glasses"),
    EmojiEntry("🕶️", "sunglasses"),
    EmojiEntry("🥽", "goggles"),
    EmojiEntry("🧳", "luggage"),
    EmojiEntry("🌂", "closed umbrella"),
    EmojiEntry("☂️", "umbrella"),
    EmojiEntry("🎒", "backpack"),
    EmojiEntry("👑", "crown"),
    EmojiEntry("👒", "woman's hat"),
    EmojiEntry("🎩", "top hat"),
    EmojiEntry("🧢", "billed cap"),
    EmojiEntry("🪖", "military helmet"),
    EmojiEntry("💄", "lipstick"),
    EmojiEntry("💍", "ring"),
    EmojiEntry("💎", "gem stone"),
    EmojiEntry("📱", "mobile phone"),
    EmojiEntry("📲", "mobile phone with arrow"),
    EmojiEntry("💻", "laptop"),
    EmojiEntry("⌨️", "keyboard"),
    EmojiEntry("🖥️", "desktop computer"),
    EmojiEntry("🖨️", "printer"),
    EmojiEntry("🖱️", "computer mouse"),
    EmojiEntry("💽", "computer disk"),
    EmojiEntry("💾", "floppy disk"),
    EmojiEntry("💿", "optical disk"),
    EmojiEntry("📀", "dvd"),
    EmojiEntry("🔋", "battery"),
    EmojiEntry("🔌", "electric plug"),
    EmojiEntry("💡", "light bulb"),
    EmojiEntry("🔦", "flashlight"),
    EmojiEntry("🕯️", "candle"),
    EmojiEntry("📔", "notebook with decorative cover"),
    EmojiEntry("📕", "closed book"),
    EmojiEntry("📖", "open book"),
    EmojiEntry("📗", "green book"),
    EmojiEntry("📘", "blue book"),
    EmojiEntry("📙", "orange book"),
    EmojiEntry("📚", "books"),
    EmojiEntry("📓", "notebook"),
    EmojiEntry("📒", "ledger"),
    EmojiEntry("📃", "page with curl"),
    EmojiEntry("📜", "scroll"),
    EmojiEntry("📄", "page facing up"),
    EmojiEntry("📰", "newspaper"),
    EmojiEntry("📁", "file folder"),
    EmojiEntry("📂", "open file folder"),
    EmojiEntry("📅", "calendar"),
    EmojiEntry("📆", "tear-off calendar"),
    EmojiEntry("📌", "pushpin"),
    EmojiEntry("📎", "paperclip"),
    EmojiEntry("🖇️", "linked paperclips"),
    EmojiEntry("📏", "straight ruler"),
    EmojiEntry("📐", "triangular ruler"),
    EmojiEntry("✂️", "scissors"),
    EmojiEntry("🗑️", "wastebasket"),
    EmojiEntry("🔒", "locked"),
    EmojiEntry("🔓", "unlocked"),
    EmojiEntry("🔑", "key"),
    EmojiEntry("🗝️", "old key"),
    EmojiEntry("🔨", "hammer"),
    EmojiEntry("🪓", "axe"),
    EmojiEntry("⛏️", "pick"),
    EmojiEntry("🔧", "wrench"),
    EmojiEntry("🪛", "screwdriver"),
    EmojiEntry("🔩", "nut and bolt"),
    EmojiEntry("⚙️", "gear"),
    EmojiEntry("🔗", "link"),
    EmojiEntry("⛓️", "chains"),
    EmojiEntry("🪝", "hook"),
    EmojiEntry("🧲", "magnet"),
    EmojiEntry("💊", "pill"),
    EmojiEntry("🩹", "adhesive bandage"),
    EmojiEntry("🩺", "stethoscope"),
    EmojiEntry("🪬", "hamsa"),
    EmojiEntry("🚬", "cigarette"),
    EmojiEntry("⚰️", "coffin"),
    EmojiEntry("🪦", "headstone"),
    EmojiEntry("🏺", "amphora"),
    EmojiEntry("🔭", "telescope"),
    EmojiEntry("🔬", "microscope"),
    EmojiEntry("🧪", "test tube"),
    EmojiEntry("🧫", "petri dish"),
    EmojiEntry("🧬", "dna"),
    EmojiEntry("🎵", "musical note"),
    EmojiEntry("🎶", "musical notes"),
    EmojiEntry("🎙️", "studio microphone"),
    EmojiEntry("🎤", "microphone"),
    EmojiEntry("🎧", "headphone"),
    EmojiEntry("📻", "radio"),
    EmojiEntry("🎷", "saxophone"),
    EmojiEntry("🪗", "accordion"),
    EmojiEntry("🎸", "guitar"),
    EmojiEntry("🎹", "musical keyboard"),
    EmojiEntry("🎺", "trumpet"),
    EmojiEntry("🎻", "violin"),
    EmojiEntry("🪕", "banjo"),
    EmojiEntry("🥁", "drum"),
    EmojiEntry("🪘", "long drum"),
    EmojiEntry("📷", "camera"),
    EmojiEntry("📸", "camera with flash"),
    EmojiEntry("📹", "video camera"),
    EmojiEntry("🎥", "movie camera"),
    EmojiEntry("📽️", "film projector"),
    EmojiEntry("🎬", "clapper board"),
    EmojiEntry("📺", "television"),
    EmojiEntry("📞", "telephone receiver"),
    EmojiEntry("📟", "pager"),
    EmojiEntry("📠", "fax machine"),
)

// Symbols
private val SYMBOLS = listOf(
    EmojiEntry("❤️‍🔥", "heart on fire"),
    EmojiEntry("❤️‍🩹", "mending heart"),
    EmojiEntry("🩷", "pink heart"),
    EmojiEntry("🩵", "light blue heart"),
    EmojiEntry("🩶", "grey heart"),
    EmojiEntry("♈", "Aries"),
    EmojiEntry("♉", "Taurus"),
    EmojiEntry("♊", "Gemini"),
    EmojiEntry("♋", "Cancer"),
    EmojiEntry("♌", "Leo"),
    EmojiEntry("♍", "Virgo"),
    EmojiEntry("♎", "Libra"),
    EmojiEntry("♏", "Scorpio"),
    EmojiEntry("♐", "Sagittarius"),
    EmojiEntry("♑", "Capricorn"),
    EmojiEntry("♒", "Aquarius"),
    EmojiEntry("♓", "Pisces"),
    EmojiEntry("⛎", "Ophiuchus"),
    EmojiEntry("🔀", "shuffle tracks"),
    EmojiEntry("🔁", "repeat"),
    EmojiEntry("🔂", "repeat single"),
    EmojiEntry("▶️", "play"),
    EmojiEntry("⏩", "fast-forward"),
    EmojiEntry("⏪", "rewind"),
    EmojiEntry("🔼", "upwards"),
    EmojiEntry("🔽", "downwards"),
    EmojiEntry("⏸️", "pause"),
    EmojiEntry("⏹️", "stop"),
    EmojiEntry("⏺️", "record"),
    EmojiEntry("⏏️", "eject"),
    EmojiEntry("🔅", "dim"),
    EmojiEntry("🔆", "bright"),
    EmojiEntry("📶", "antenna bars"),
    EmojiEntry("📳", "vibration mode"),
    EmojiEntry("📴", "mobile phone off"),
    EmojiEntry("♻️", "recycling"),
    EmojiEntry("⚜️", "fleur-de-lis"),
    EmojiEntry("🔱", "trident"),
    EmojiEntry("📛", "name badge"),
    EmojiEntry("🔰", "Japanese symbol for beginner"),
    EmojiEntry("⭕", "hollow red circle"),
    EmojiEntry("✅", "check mark"),
    EmojiEntry("☑️", "check box with check"),
    EmojiEntry("✔️", "check mark"),
    EmojiEntry("❌", "cross mark"),
    EmojiEntry("❎", "cross mark button"),
    EmojiEntry("➕", "plus"),
    EmojiEntry("➖", "minus"),
    EmojiEntry("➗", "divide"),
    EmojiEntry("✖️", "multiply"),
    EmojiEntry("💲", "heavy dollar sign"),
    EmojiEntry("💱", "currency exchange"),
    EmojiEntry("©️", "copyright"),
    EmojiEntry("®️", "registered"),
    EmojiEntry("™️", "trade mark"),
    EmojiEntry("🔟", "keycap 10"),
    EmojiEntry("🔢", "input numbers"),
    EmojiEntry("🔣", "input symbols"),
    EmojiEntry("🔤", "input latin letters"),
    EmojiEntry("🅰️", "A button"),
    EmojiEntry("🆎", "AB button"),
    EmojiEntry("🅱️", "B button"),
    EmojiEntry("🆑", "CL button"),
    EmojiEntry("🆒", "COOL button"),
    EmojiEntry("🆓", "FREE button"),
    EmojiEntry("ℹ️", "information"),
    EmojiEntry("🆔", "ID button"),
    EmojiEntry("Ⓜ️", "circled M"),
    EmojiEntry("🆕", "NEW button"),
    EmojiEntry("🆖", "NG button"),
    EmojiEntry("🅾️", "O button"),
    EmojiEntry("🆗", "OK button"),
    EmojiEntry("🅿️", "P button"),
    EmojiEntry("🆘", "SOS button"),
    EmojiEntry("🆙", "UP button"),
    EmojiEntry("🆚", "VS button"),
    EmojiEntry("🈁", "Japanese here button"),
    EmojiEntry("🈂️", "Japanese service charge button"),
    EmojiEntry("🔴", "red circle"),
    EmojiEntry("🟠", "orange circle"),
    EmojiEntry("🟡", "yellow circle"),
    EmojiEntry("🟢", "green circle"),
    EmojiEntry("🔵", "blue circle"),
    EmojiEntry("🟣", "purple circle"),
    EmojiEntry("🟤", "brown circle"),
    EmojiEntry("⚫", "black circle"),
    EmojiEntry("⚪", "white circle"),
    EmojiEntry("🟥", "red square"),
    EmojiEntry("🟧", "orange square"),
    EmojiEntry("🟨", "yellow square"),
    EmojiEntry("🟩", "green square"),
    EmojiEntry("🟦", "blue square"),
    EmojiEntry("🟪", "purple square"),
    EmojiEntry("🟫", "brown square"),
    EmojiEntry("⬛", "black large square"),
    EmojiEntry("⬜", "white large square"),
    EmojiEntry("◼️", "black medium square"),
    EmojiEntry("◻️", "white medium square"),
    EmojiEntry("🔶", "large orange diamond"),
    EmojiEntry("🔷", "large blue diamond"),
    EmojiEntry("🔸", "small orange diamond"),
    EmojiEntry("🔹", "small blue diamond"),
    EmojiEntry("🔺", "red triangle pointed up"),
    EmojiEntry("🔻", "red triangle pointed down"),
    EmojiEntry("💠", "diamond with a dot"),
    EmojiEntry("🔘", "radio button"),
    EmojiEntry("🔳", "white square button"),
    EmojiEntry("🔲", "black square button"),
)

// Flags (subset)
private val FLAGS = listOf(
    EmojiEntry("🏳️", "white flag"),
    EmojiEntry("🏴", "black flag"),
    EmojiEntry("🏁", "chequered flag"),
    EmojiEntry("🚩", "triangular flag"),
    EmojiEntry("🏳️‍🌈", "rainbow flag"),
    EmojiEntry("🏳️‍⚧️", "transgender flag"),
    EmojiEntry("🏴‍☠️", "pirate flag"),
    EmojiEntry("🇦🇷", "flag Argentina"),
    EmojiEntry("🇦🇺", "flag Australia"),
    EmojiEntry("🇧🇷", "flag Brazil"),
    EmojiEntry("🇨🇦", "flag Canada"),
    EmojiEntry("🇨🇳", "flag China"),
    EmojiEntry("🇩🇪", "flag Germany"),
    EmojiEntry("🇪🇸", "flag Spain"),
    EmojiEntry("🇫🇷", "flag France"),
    EmojiEntry("🇬🇧", "flag United Kingdom"),
    EmojiEntry("🇮🇳", "flag India"),
    EmojiEntry("🇮🇹", "flag Italy"),
    EmojiEntry("🇯🇵", "flag Japan"),
    EmojiEntry("🇰🇷", "flag South Korea"),
    EmojiEntry("🇲🇽", "flag Mexico"),
    EmojiEntry("🇳🇱", "flag Netherlands"),
    EmojiEntry("🇵🇹", "flag Portugal"),
    EmojiEntry("🇷🇺", "flag Russia"),
    EmojiEntry("🇸🇪", "flag Sweden"),
    EmojiEntry("🇹🇷", "flag Turkey"),
    EmojiEntry("🇺🇦", "flag Ukraine"),
    EmojiEntry("🇺🇸", "flag United States"),
    EmojiEntry("🇿🇦", "flag South Africa"),
)
