#!/usr/bin/env bash
# Generate docs/components-index.md — a flat catalogue of reusable UI building
# blocks so we reuse instead of recreating them. Lists every public Compose
# @Composable under uiComposeMain/ui/components and every React FC under
# webMain/web/{components,modals}, each with the first line of its KDoc.
#
# Run from anywhere: ./scripts/gen-component-index.sh
# Regenerate whenever a component is added or removed; consult the output before
# building any new UI element (see CLAUDE.md "Shared UI Components").
set -euo pipefail
cd "$(dirname "$0")/.."

SRC=composeApp/src
OUT=docs/components-index.md
mkdir -p docs

# Shared awk preamble: strip comment markers and indentation from a line.
read -r -d '' STRIP <<'AWK' || true
function strip(t){
  sub(/^[ \t]*/,"",t); sub(/^\/\*\*+[ \t]*/,"",t); sub(/^\/\/[ \t]*/,"",t)
  sub(/^\*+[ \t]?/,"",t); sub(/[ \t]*\*\/[ \t]*$/,"",t); sub(/[ \t]+$/,"",t)
  gsub(/\|/,"/",t); return t
}
AWK

# Public @Composable functions under ui/components. The purpose is the first
# meaningful KDoc line directly above (the @Composable annotation does not break
# the link); plain helper funs without @Composable are skipped.
emit_compose() {
  find "$SRC/uiComposeMain/kotlin/org/nostr/nostrord/ui/components" -name '*.kt' | sort | while read -r f; do
    rel=${f#"$SRC/"}
    awk -v file="$rel" "$STRIP"'
      /^[ \t]*(\/\/|\/\*\*|\*)/ { c=strip($0); if(c!="" && c!="/" && pend=="") pend=c; next }
      /^[ \t]*@Composable/      { composable=1; next }
      /^[ \t]*@/                { next }
      /^fun [A-Z][A-Za-z0-9_]*[ ]*\(/ {
        if (composable) { name=$2; sub(/\(.*/,"",name); printf "%s\t%s\t%s\n", name, file, (pend==""?"—":pend) }
        composable=0; pend=""; next
      }
      /^[ \t]*$/ { next }
      { pend=""; composable=0 }
    ' "$f"
  done
}

# React FC components under web/components and web/modals. Handles both the
# single-line (`val X = FC<…> {`) and split (`val X =` then `FC<…>`) forms.
emit_web() {
  for dir in components modals; do
    d="$SRC/webMain/kotlin/org/nostr/nostrord/web/$dir"
    [ -d "$d" ] || continue
    find "$d" -name '*.kt' | sort | while read -r f; do
      rel=${f#"$SRC/"}
      awk -v file="$rel" "$STRIP"'
        /^[ \t]*(\/\/|\/\*\*|\*)/ { c=strip($0); if(c!="" && c!="/" && pend=="") pend=c; next }
        /^[ \t]*@/ { next }
        /^val [A-Z][A-Za-z0-9_]* =/ {
          cand=$2; candp=(pend==""?"—":pend); pend=""
          if ($0 ~ /FC[ \t]*</) { printf "%s\t%s\t%s\n", cand, file, candp; cand=""; waiting=0 }
          else waiting=1
          next
        }
        waiting && /FC[ \t]*</ { printf "%s\t%s\t%s\n", cand, file, candp; waiting=0; cand=""; next }
        /^[ \t]*$/ { next }
        { pend=""; waiting=0 }
      ' "$f"
    done
  done
}

render() {
  emit_"$1" | sort -f | while IFS=$'\t' read -r name file purpose; do
    [ -n "$name" ] || continue
    printf '| `%s` | %s | %s |\n' "$name" "$file" "${purpose:0:140}"
  done
}

{
  echo "# Components index"
  echo
  echo "_Generated by \`scripts/gen-component-index.sh\` — do not edit by hand._"
  echo
  echo "Reuse one of these before creating any new UI element. If none fits, extend the"
  echo "closest match rather than cloning it. When a new component supersedes an old one,"
  echo "delete the old one in the same change so the catalogue never lists a dead screen."
  echo
  echo "## Compose (uiComposeMain/ui/components)"
  echo
  echo "| Component | File | Purpose |"
  echo "|---|---|---|"
  render compose
  echo
  echo "## Web React (webMain/web/components, web/modals)"
  echo
  echo "| Component | File | Purpose |"
  echo "|---|---|---|"
  render web
} > "$OUT"

echo "Wrote $OUT ($(grep -c '^| `' "$OUT") components)"
