package org.nostr.nostrord.utils

import kotlin.random.Random

/**
 * Generates short, pronounceable, memorable ids (e.g. "gritfeljaem", "tallutmou")
 * by chaining consonant-vowel-coda syllables. Used for autogenerated NIP-29
 * group ids instead of opaque hex strings (issue #201).
 */
object ReadableId {
    private val onsets = listOf(
        "b", "c", "d", "f", "g", "h", "j", "k", "l", "m", "n", "p", "r", "s", "t", "v",
        "br", "cr", "dr", "fr", "gr", "pr", "tr", "bl", "cl", "fl", "gl", "pl", "sl",
        "sh", "ch", "th", "st", "sk",
    )
    private val nuclei = listOf("a", "e", "i", "o", "u", "ae", "ei", "io", "ou")
    private val codas = listOf("", "", "", "n", "r", "s", "t", "d", "l", "m", "k")

    fun generate(syllables: Int = 3, random: Random = Random): String = buildString {
        repeat(syllables) {
            append(onsets.random(random))
            append(nuclei.random(random))
            append(codas.random(random))
        }
    }
}
